version: "3.9"

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URI=mongodb://root:password@mongodb:27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    restart: always

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  ffmpeg:
    image: jrottenberg/ffmpeg:6.0-ubuntu
    container_name: ffmpeg_service
    volumes:
      - ./videos:/videos
    entrypoint: ["tail", "-f", "/dev/null"]  # keep container alive
    restart: always

volumes:
  mongo_data: