services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URI=mongodb://root:password@mongodb:27017/?authSource=admin
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
      - ./videos:/videos
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  ffmpeg:
    image: jrottenberg/ffmpeg:latest
    container_name: ffmpeg_service
    volumes:
      - ./videos:/videos
    entrypoint: ["tail", "-f", "/dev/null"]
    restart: always

volumes:
  mongo_data: